<svelte:head>
  <script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "BlogPosting",
      "headline": "Formalized Zeckendorf Theorem",
      "author": {
        "@type": "Person",
        "name": "Christian Dalvit",
        "url": "https://chrisdalvit.github.io"
      },
      "datePublished": "2025-04-01",
      "dateModified": "2025-04-01",
      "description": "Verified formalization of Zeckendorf's theorem in Isabelle/HOL. First the proof af the Zeckendorf theorem is presented. Then the verified formalization of the Zeckendorf theorem in Isabelle/HOL is explained. The formalization is published in the Archive of Formal Proofs.",
      "mainEntityOfPage": "https://chrisdalvit.github.io/zeckendorf-theorem"
    }
  </script>
  <meta name="keywords" content="Math, Isabelle/HOL, Theorem Proving, Verification, Zeckendorf Theorem, Theoretical Computer Science, Archive of Formal Proofs">
</svelte:head>

<script lang="ts">
    import Katex from 'svelte-katex';

    import ArticleTemplate from "$lib/ArticleTemplate.svelte";
    import ArticleAbstract from "$lib/ArticleAbstract.svelte";
    import ArticleSection from "$lib/ArticleSection.svelte";
    import Citation from "$lib/Citation.svelte";
    import References from "$lib/References.svelte";
    import "./isabelle.css"

    let citations = {
        theoremPaper: {
            index: 1,
            title: "Voorstelling van natuurlijke getallen door een som van getallen van Fibonacci",
            author: "Gerrit C. Lekkerkerker",
            year: "1951 (Accessed 21.12.2024)",
            link: "https://ir.cwi.nl/pub/6922/6922D.pdf"
        },
        differentUniquenessProof: {
            index: 2,
            title: "What is Zeckendorf's Theorem?",
            author: "Nik Henderson",
            year: "2016",
            link: "https://math.osu.edu/sites/math.osu.edu/files/henderson_zeckendorf.pdf"
        },
        isabelle: {
            index: 3,
            title: "Isabelle/HOL: a proof assistant for higher-order logic",
            author: "Nipkow, Tobias and Paulson, Lawrence C and Wenzel, Markus",
            year: "2002",
            link: "https://link.springer.com/book/10.1007/3-540-45949-9"
        }
    }
</script>

<ArticleTemplate title="Formalized Zeckendorf Theorem" date="1. April 2025">
    <ArticleAbstract>
      This blog post presents my formalized proof of the Zeckendorf Theorem using the theorem prover Isabelle/HOL <Citation citation={citations.isabelle} />. 
      First, I'll describe the original proof, and then I will discuss my formalization. The formal proof is available on the <a href="https://www.isa-afp.org/entries/Zeckendorf.html" target="_blank">Archive of Formal Proofs</a> and on <a href="https://github.com/chrisdalvit/zeckendorf-theorem" target="_blank">GitHub</a>.
    </ArticleAbstract>
    <ArticleSection title="Proof" id="proof">
        <p>
          Informally, the Zeckendorf theorem states that every positive integer can be represented uniquely as the sum of one or more distinct Fibonacci numbers, such that the sum does not include any two consecutive Fibonacci numbers. Fibonacci numbers are a sequence of natural numbers defined as
        </p>  
        <Katex displayMode>
            F_0 = 0 \qquad F_1 = 1
        </Katex>
        <Katex displayMode>
            F_n  = F_{"{n-1}"} + F_{"{n-2}"}
        </Katex>
        <p>
          for <Katex>n &gt; 1</Katex>. More precisely, the theorem states that if <Katex>N</Katex> is any positive integer, there exist positive integers <Katex>c_i \ge 2</Katex>, with <Katex>c_{"{i+1}"} > c_i + 1</Katex>, such that
        </p>      
        <Katex displayMode> 
            N = \sum_{"{i=0}"}^k F_{"{c_i}"}
        </Katex>
        <p>
          Let's now walk through the original proof from the Dutch mathematician Gerrit Lekkerkerker <Citation citation={citations.theoremPaper} />. We prove the theorem by induction over <Katex>N</Katex>. For <Katex>N = 1</Katex>, we choose <Katex>c_0 = 2</Katex> and have
        </p>      
        <Katex displayMode>
            \sum_{"{i = 0}"}^0 F_{"{c_i}"} = F_{"{c_0}"} = F_2 = 1 
        </Katex>
        <p>
          It is obvious that this representation is unique. Now we can continue by assuming that the Zeckendorf theorem holds for <Katex>1, \dots, N-1</Katex> and proving the theorem for <Katex>N</Katex>.  
          We can observe that every positive natural number is either a Fibonacci number or lies between two consecutive Fibonacci numbers. Therefore, for every <Katex>N > 0</Katex>, there exists a Fibonacci number <Katex>F_i</Katex> such that
        </p>
        <Katex displayMode> 
            \begin{"{equation}"}
                F_i \le N &lt F_{"{i+1}"}
            \end{"{equation}"}
        </Katex>
        <p>
          If <Katex>N</Katex> is not a Fibonacci number, the first inequality is strict. If <Katex>N</Katex> is a Fibonacci number, there is nothing to prove (since <Katex>N</Katex> can be represented as a sum with <Katex>F_i</Katex> as the only element). Therefore, we will continue assuming <Katex>N</Katex> is not a Fibonacci number. 
      
          By subtracting <Katex>F_i</Katex> from equation (1), we obtain  
          <Katex> 
              0 &lt N - F_i &lt F_{"{i+1}"} - F_i
          </Katex>.  
          By the definition of Fibonacci numbers, we can rewrite the inequality as  
          <Katex> 
              0 &lt N - F_i &lt F_{"{i-1}"}
          </Katex>.  
          Using the induction hypothesis, we can represent <Katex>N - F_i</Katex> as a sum of Fibonacci numbers.
        </p>    
        <Katex displayMode>
            N - F_i = \sum_{"{j=0}"}^k F_{"{c_j}"} \quad \text{"{with}"} \quad c_i \ge 2,~ c_{"{j+1}"} > c_j + 1
        </Katex>
        <p>
          By adding <Katex>F_i</Katex> to this sum, we obtain a representation of <Katex>N</Katex> as a sum of Fibonacci numbers.
        </p>    
        <Katex displayMode>
            N = F_i + \sum_{"{j=0}"}^k F_{"{c_j}"}
        </Katex>
        <p>
          As a result of <Katex>N - F_i &lt F_{"{i-1}"}</Katex>, we can deduce that <Katex>F_i</Katex> and <Katex>F_{"{i-1}"}</Katex> are not in the sum. Therefore, <Katex>i &gt c_k + 1</Katex>. From the induction hypothesis, we know that the representation of <Katex>N - F_i</Katex> is unique. Thus, the representation of <Katex>N</Katex> is also unique. A different proof of the uniqueness of the representation can be found in the paper by Nik Henderson <Citation citation={citations.differentUniquenessProof} />.
      </p>      
    </ArticleSection>
    <ArticleSection title="Isabelle/HOL Formalization" id="isabelle-hol-formalization">
        <p>
          After revisiting the original proof, we can now discuss the main steps of my formalization of the Zeckendorf theorem in Isabelle/HOL <Citation citation={citations.isabelle} />. The formal proof is available in the <a href="https://www.isa-afp.org/entries/Zeckendorf.html" target="_blank">Archive of Formal Proofs</a>.
        </p>    
        <p>
          The definition of Fibonacci numbers is already implemented in Isabelle/HOL's Number Theory library. After introducing some auxiliary lemmas and definitions, we can prove inequality (1) for the case where <Katex>N</Katex> is not a Fibonacci number.
        </p>      
        <pre class="source">
  <span class="keyword1 command">lemma</span> no_fib_betw_fibs: 
    <span class="keyword2 command">assumes</span> "¬ is_fib <span class="free">n</span>"
    <span class="keyword2 command">shows</span> "∃ <span class="bound">i</span>. fib <span class="bound">i</span> &lt <span class="free">n</span> ∧ <span class="free">n</span> &lt fib (Suc <span class="bound">i</span>)" 
  <span class="keyword1 command">proof</span> - 
    <span class="keyword1 command">have</span> finite_le_fib: "finite {'{'}<span class="bound">i</span>. fib <span class="bound">i</span> &lt <span class="free">n</span>{'}'}" 
        <span class="keyword1 command">using</span> finite_smaller_fibs <span class="keyword1 command">by</span> auto
    <span class="keyword3 command">obtain</span> <span class="skolem">i</span> <span class="keyword2 command">where</span> max_def: "<span class="skolem">i</span> = Max {'{'}<span class="bound">i</span>. fib <span class="bound">i</span> &lt <span class="free">n</span>{'}'}" <span class="keyword1 command">by</span> blast
    <span class="keyword3 command">show</span> "∃ <span class="bound">i</span>. fib <span class="bound">i</span> &lt <span class="free">n</span> ∧ <span class="free">n</span> &lt fib (Suc <span class="bound">i</span>)"
    <span class="keyword1 command">proof</span>(intro exI conjI)
        <span class="keyword1 command">have</span> "(Suc <span class="skolem">i</span>) ∉ {'{'}<span class="bound">i</span>. fib <span class="bound">i</span> &lt <span class="free">n</span>{'}'}" 
            <span class="keyword1 command">using</span> max_def Max_ge Suc_n_not_le_n finite_le_fib <span class="keyword1 command">by</span> blast
        <span class="keyword3 command">thus</span> "fib (Suc <span class="skolem">i</span>) &gt <span class="free">n</span>" 
            <span class="keyword1 command">using</span> ‹¬ is_fib <span class="free">n</span>› fib_implies_is_fib linorder_less_linear <span class="keyword1 command">by</span> blast
    <span class="keyword1 command">qed</span>(insert max_def Max_in ‹¬ is_fib n› finite_le_fib no_fib_implies_le_fib_idx_set, auto) 
  <span class="keyword1 command">qed</span></pre>
  <p>
    Here, I use the fact that the set of indices of Fibonacci numbers smaller than <Katex>N</Katex> is finite. By definition, the maximum of this set, <Katex>i</Katex>, must satisfy the inequalities in (1). Next, we can already prove the existence of the Zeckendorf representation.
  </p>
    <pre class="source">
  <span class="keyword1"><span class="command"><span class="entity_def" id="offset_9428..9435">theorem</span></span></span><span> </span><span class="entity_def" id="Zeckendorf.zeckendorf_existence|fact"><span class="entity_def" id="Zeckendorf.zeckendorf_existence|thm"><span>zeckendorf_existence</span></span></span><span class="main"><span>:</span></span><span>
    </span><span class="keyword2"><span class="keyword"><span>assumes</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>n</span></span><span> </span><span class="main"><span>&gt;</span></span><span> </span><span class="main"><span>0</span></span><span>"</span></span></span><span>
    </span><span class="keyword2"><span class="keyword"><span>shows</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="main"><span>∃</span></span><span> </span><span class="bound"><span>c</span></span><span> </span><span class="bound"><span>k</span></span><span class="main"><span>.</span></span><span> </span><span class="free"><span>n</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="main"><span>(</span></span><span class="main"><span>∑</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>=</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="bound"><span>k</span></span><span class="main"><span>.</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="bound"><span>c</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>)</span></span><span class="main"><span>)</span></span><span> </span><span class="main"><span>∧</span></span><span> </span><span>inc_seq_on</span><span> </span><span class="bound"><span>c</span></span><span> </span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="bound"><span>k</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span class="main"><span>{'}'}</span></span><span> </span><span class="main"><span>∧</span></span><span> </span><span class="main"><span>(</span></span><span class="main"><span>∀</span></span><span class="bound"><span>i</span></span><span class="main"><span>∈</span></span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="bound"><span>k</span></span><span class="main"><span>{'}'}</span></span><span class="main"><span>.</span></span><span> </span><span class="bound"><span>c</span></span><span> </span><span class="bound"><span>i</span></span><span> </span><span class="main"><span>≥</span></span><span> </span><span class="numeral"><span>2</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span> 
        </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>assms</span><span>
  </span><span class="keyword1"><span class="command"><span>proof</span></span></span><span class="main"><span>(</span></span><span class="operator"><span>induct</span></span><span> </span><span class="quoted"><span class="free"><span>n</span></span></span><span> </span><span class="quasi_keyword"><span>rule</span></span><span class="main"><span class="main"><span>:</span></span></span><span> </span><span>nat_less_induct</span><span class="main"><span>)</span></span><span>
    </span><span class="keyword3"><span class="command"><span>case</span></span></span><span> </span><span class="main"><span>(</span></span><span class="entity_def" id="offset_9627..9628">1</span><span> </span><span class="skolem"><span>n</span></span><span class="main"><span>)</span></span><span>
    </span><span class="keyword1"><span class="command"><span>then</span></span></span><span> </span><span class="keyword3"><span class="command"><span>show</span></span></span><span> </span><span class="var"><span class="quoted"><span class="var"><span>?case</span></span></span></span><span>
    </span><span class="keyword1"><span class="command"><span>proof</span></span></span><span class="main"><span>(</span></span><span class="operator"><span>cases</span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span>is_fib</span><span> </span><span class="skolem"><span>n</span></span><span>"</span></span></span><span class="main"><span>)</span></span><span>
        </span><span class="keyword3"><span class="command"><span>case</span></span></span><span> </span><span class="entity_def" id="offset_9685..9690">False</span><span>
        </span><span class="keyword3"><span class="command"><span>obtain</span></span></span><span> </span><span class="skolem"><span class="skolem"><span>i</span></span></span><span> </span><span class="keyword2"><span class="keyword"><span>where</span></span></span><span> </span><span class="entity_def" id="offset_9710..9716">bounds</span><span class="main"><span>:</span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span>fib</span><span> </span><span class="skolem"><span>i</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span class="skolem"><span>n</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="skolem"><span>n</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span>Suc</span><span> </span><span class="skolem"><span>i</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="skolem"><span>i</span></span><span> </span><span class="main"><span>&gt;</span></span><span> </span><span class="main"><span>0</span></span><span>"</span></span></span><span>
            </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>no_fib_betw_fibs</span><span> </span><span>1</span><span class="main"><span>(</span></span><span>2</span><span class="main"><span>)</span></span><span> </span><span>False</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>force</span></span><span>
        </span><span class="keyword1"><span class="command"><span>then</span></span></span><span> </span><span class="keyword3"><span class="command"><span>obtain</span></span></span><span> </span><span class="skolem"><span class="skolem"><span>c</span></span></span><span> </span><span class="skolem"><span class="skolem"><span>k</span></span></span><span> </span><span class="keyword2"><span class="keyword"><span>where</span></span></span><span> </span><span class="entity_def" id="offset_9831..9834">seq</span><span class="main"><span>:</span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="main"><span>(</span></span><span class="skolem"><span>n</span></span><span> </span><span class="main"><span>-</span></span><span> </span><span>fib</span><span> </span><span class="skolem"><span>i</span></span><span class="main"><span>)</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="main"><span>(</span></span><span class="main"><span>∑</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>=</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="skolem"><span>k</span></span><span class="main"><span>.</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="skolem"><span>c</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>)</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span>inc_seq_on</span><span> </span><span class="skolem"><span>c</span></span><span> </span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="skolem"><span>k</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span class="main"><span>{'}'}</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="main"><span>∀</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>∈</span></span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="skolem"><span>k</span></span><span class="main"><span>{'}'}</span></span><span class="main"><span>.</span></span><span> </span><span class="skolem"><span>c</span></span><span> </span><span class="bound"><span>i</span></span><span> </span><span class="main"><span>≥</span></span><span> </span><span class="numeral"><span>2</span></span><span>"</span></span></span><span>
            </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>1</span><span> </span><span>fib_neq_0_nat</span><span> </span><span>zero_less_diff</span><span> </span><span>diff_less</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>metis</span></span><span>
        </span><span class="keyword1"><span class="command"><span>let</span></span></span><span> </span><span class="var"><span class="quoted"><span class="var"><span>?c'</span></span></span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="main"><span>(</span></span><span class="main"><span>λ</span></span><span> </span><span class="bound"><span>n</span></span><span class="main"><span>.</span></span><span> </span><span class="keyword1"><span>if</span></span><span> </span><span class="bound"><span>n</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="skolem"><span>k</span></span><span class="main"><span>+</span></span><span class="main"><span>1</span></span><span> </span><span class="keyword1"><span>then</span></span><span> </span><span class="skolem"><span>i</span></span><span> </span><span class="keyword1"><span>else</span></span><span> </span><span class="skolem"><span>c</span></span><span> </span><span class="bound"><span>n</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span>
        </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="entity_def" id="offset_10041..10052">diff_le_fib</span><span class="main"><span>:</span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="skolem"><span>n</span></span><span> </span><span class="main"><span>-</span></span><span> </span><span>fib</span><span> </span><span class="skolem"><span>i</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span>fib</span><span class="main"><span>(</span></span><span class="skolem"><span>i</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span>
            </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>bounds</span><span> </span><span>fib2</span><span> </span><span>not0_implies_Suc</span><span class="main"><span>[</span></span><span class="operator"><span>of</span></span><span> </span><span class="quoted"><span class="skolem"><span>i</span></span></span><span class="main"><span>]</span></span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>auto</span></span><span>
        </span><span class="keyword1"><span class="command"><span>hence</span></span></span><span> </span><span class="entity_def" id="offset_10142..10151">ck_lt_fib</span><span class="main"><span>:</span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="skolem"><span>c</span></span><span> </span><span class="skolem"><span>k</span></span><span class="main"><span>)</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span>fib</span><span> </span><span class="skolem"><span>i</span></span><span>"</span></span></span><span> 
            </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>fib_Suc_mono</span><span class="main"><span>[</span></span><span class="operator"><span>of</span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="skolem"><span>i</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span>"</span></span></span><span class="main"><span>]</span></span><span> </span><span>bounds</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="main"><span>(</span></span><span class="operator"><span>simp</span></span><span> </span><span class="quasi_keyword"><span>add</span></span><span class="main"><span class="main"><span>:</span></span></span><span> </span><span>sum.last_plus</span><span> </span><span>seq</span><span class="main"><span>)</span></span><span>
        </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span>inc_seq_on</span><span> </span><span class="var"><span>?c'</span></span><span> </span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="skolem"><span>k</span></span><span class="main"><span>{'}'}</span></span><span>"</span></span></span><span>
            </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>inc_seq_on_aux</span><span class="main"><span>[</span></span><span class="operator"><span>OF</span></span><span> </span><span>seq</span><span class="main"><span class="main"><span>(</span></span></span><span>2</span><span class="main"><span class="main"><span>)</span></span></span><span> </span><span>diff_le_fib</span><span> </span><span>ck_lt_fib</span><span> </span><span>seq</span><span class="main"><span class="main"><span>(</span></span></span><span>1</span><span class="main"><span class="main"><span>)</span></span></span><span class="main"><span>]</span></span><span> </span><span>One_nat_def</span><span> 
                </span><span>inc_seq_on_def</span><span> </span><span>leI</span><span> </span><span>seq</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>force</span></span><span>
        </span><span class="keyword1"><span class="command"><span>moreover</span></span></span><span> </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="skolem"><span>n</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="main"><span>(</span></span><span class="main"><span>∑</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>=</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="skolem"><span>k</span></span><span class="main"><span>+</span></span><span class="main"><span>1</span></span><span class="main"><span>.</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="var"><span>?c'</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>)</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span> 
            </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>bounds</span><span> </span><span>seq</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>simp</span></span><span>
        </span><span class="keyword1"><span class="command"><span>moreover</span></span></span><span> </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="main"><span>∀</span></span><span> </span><span class="bound"><span>i</span></span><span> </span><span class="main"><span>∈</span></span><span> </span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="skolem"><span>k</span></span><span class="main"><span>+</span></span><span class="main"><span>1</span></span><span class="main"><span>{'}'}</span></span><span class="main"><span>.</span></span><span> </span><span class="var"><span>?c'</span></span><span> </span><span class="bound"><span>i</span></span><span> </span><span class="main"><span>≥</span></span><span> </span><span class="numeral"><span>2</span></span><span>"</span></span></span><span> 
            </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>seq</span><span> </span><span>bounds</span><span> </span><span>fib2</span><span> </span><span>not0_implies_Suc</span><span class="main"><span>[</span></span><span class="operator"><span>of</span></span><span> </span><span class="quoted"><span class="skolem"><span>i</span></span></span><span class="main"><span>]</span></span><span> </span><span>atLeastAtMost_iff</span><span> 
                </span><span>diff_is_0_eq'</span><span> </span><span>less_nat_zero_code</span><span> </span><span>not_less_eq_eq</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>fastforce</span></span><span>
        </span><span class="keyword1"><span class="command"><span>ultimately</span></span></span><span> </span><span class="keyword3"><span class="command"><span>show</span></span></span><span> </span><span class="var"><span class="quoted"><span class="var"><span>?thesis</span></span></span></span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>fastforce</span></span><span>
    </span><span class="keyword1"><span class="command"><span>qed</span></span></span><span class="main"><span>(</span></span><span class="operator"><span>insert</span></span><span> </span><span>fib_implies_zeckendorf</span><span class="main"><span class="keyword3"><span>,</span></span></span><span> </span><span class="operator"><span>auto</span></span><span class="main"><span>)</span></span><span>
  </span><span class="keyword1"><span class="command"><span>qed</span></span></span></pre>
  <p>
    Here, I formalize the fact that every positive integer has a Zeckendorf representation. The property <code>inc_seq_on</code> is used to formalize the constraint <Katex>c_{"{j+1}"} > c_j + 1</Katex> on the domain <Katex>{'{'}0,\dots,k-1{'}'}</Katex>. Introducing the domain for the mapping <Katex>c</Katex> should simplify reasoning and make it easier to extend the mapping. The existence proof is then done by induction over <Katex>N</Katex>. Note that we use the <code>nat_less_induct</code> rule, which provides the induction hypothesis for all smaller integers. The default induction rule would not be sufficient in this case. 

    Next, I distinguish whether <Katex>N</Katex> is a Fibonacci number. If it is, the formalization is straightforward, and Isabelle can prove that case automatically using the <code>fib_implies_zeckendorf</code> lemma (in the penultimate <code>qed</code> statement). If <Katex>N</Katex> is not a Fibonacci number, we can use the previous lemma to infer the inequalities from (1). Then, we apply the induction hypothesis to find the Zeckendorf representation for <Katex>N - F_i</Katex> and define the new mapping <Katex>c'</Katex>. This new mapping simply appends <Katex>i</Katex> to the series of indices. The proof is completed by showing that <Katex>c'</Katex> satisfies the constraints and forms a Zeckendorf representation of <Katex>N</Katex>. 

    So far, only the existence of the Zeckendorf representation has been proven. However, there might be multiple representations for a given number. The next step is to prove that the representation is unique.
</p>  
    <pre class="source">
  <span class="keyword1"><span class="command"><span class="entity_def" id="offset_11684..11691">theorem</span></span></span><span> </span><span class="entity_def" id="Zeckendorf.zeckendorf_unique|fact"><span class="entity_def" id="Zeckendorf.zeckendorf_unique|thm"><span>zeckendorf_unique</span></span></span><span class="main"><span>:</span></span><span>
    </span><span class="keyword2"><span class="keyword"><span>assumes</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>n</span></span><span> </span><span class="main"><span>&gt;</span></span><span> </span><span class="main"><span>0</span></span><span>"</span></span></span><span>
    </span><span class="keyword2"><span class="keyword"><span>assumes</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>n</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="main"><span>(</span></span><span class="main"><span>∑</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>=</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="free"><span>k</span></span><span class="main"><span>.</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>c</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>)</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span>inc_seq_on</span><span> </span><span class="free"><span>c</span></span><span> </span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="free"><span>k</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span class="main"><span>{'}'}</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="main"><span>∀</span></span><span class="bound"><span>i</span></span><span class="main"><span>∈</span></span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="free"><span>k</span></span><span class="main"><span>{'}'}</span></span><span class="main"><span>.</span></span><span> </span><span class="free"><span>c</span></span><span> </span><span class="bound"><span>i</span></span><span> </span><span class="main"><span>≥</span></span><span> </span><span class="numeral"><span>2</span></span><span>"</span></span></span><span> 
    </span><span class="keyword2"><span class="keyword"><span>assumes</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>n</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="main"><span>(</span></span><span class="main"><span>∑</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>=</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="free"><span>k'</span></span><span class="main"><span>.</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>c'</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>)</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span>inc_seq_on</span><span> </span><span class="free"><span>c'</span></span><span> </span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="free"><span>k'</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span class="main"><span>{'}'}</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="main"><span>∀</span></span><span class="bound"><span>i</span></span><span class="main"><span>∈</span></span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="free"><span>k'</span></span><span class="main"><span>{'}'}</span></span><span class="main"><span>.</span></span><span> </span><span class="free"><span>c'</span></span><span> </span><span class="bound"><span>i</span></span><span> </span><span class="main"><span>≥</span></span><span> </span><span class="numeral"><span>2</span></span><span>"</span></span></span><span>
    </span><span class="keyword2"><span class="keyword"><span>shows</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>k</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="free"><span>k'</span></span><span> </span><span class="main"><span>∧</span></span><span> </span><span class="main"><span>(</span></span><span class="main"><span>∀</span></span><span> </span><span class="bound"><span>i</span></span><span> </span><span class="main"><span>∈</span></span><span> </span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="free"><span>k</span></span><span class="main"><span>{'}'}</span></span><span class="main"><span>.</span></span><span> </span><span class="free"><span>c</span></span><span> </span><span class="bound"><span>i</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="free"><span>c'</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span>
        </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>assms</span><span>
  </span><span class="keyword1"><span class="command"><span>proof</span></span></span><span class="main"><span>(</span></span><span class="operator"><span>induct</span></span><span> </span><span class="quoted"><span class="free"><span>n</span></span></span><span> </span><span class="quasi_keyword"><span>arbitrary</span></span><span class="main"><span class="main"><span>:</span></span></span><span> </span><span class="quoted"><span class="free"><span>k</span></span></span><span> </span><span class="quoted"><span class="free"><span>k'</span></span></span><span> </span><span class="quasi_keyword"><span>rule</span></span><span class="main"><span class="main"><span>:</span></span></span><span> </span><span>nat_less_induct</span><span class="main"><span>)</span></span><span>
    </span><span class="keyword3"><span class="command"><span>case</span></span></span><span> </span><span class="entity_def" id="offset_12023..12025">IH</span><span class="main"><span>:</span></span><span> </span><span class="main"><span>(</span></span><span>1</span><span> </span><span class="skolem"><span>n</span></span><span class="main"><span>)</span></span><span>
    </span><span class="keyword1"><span class="command"><span>consider</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="skolem"><span>n</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="main"><span>0</span></span><span>"</span></span></span><span> </span><span class="main"><span>|</span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="skolem"><span>n</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="main"><span>1</span></span><span>"</span></span></span><span> </span><span class="main"><span>|</span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="skolem"><span>n</span></span><span> </span><span class="main"><span>≥</span></span><span> </span><span class="numeral"><span>2</span></span><span>"</span></span></span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>linarith</span></span><span>
    </span><span class="keyword1"><span class="command"><span>then</span></span></span><span> </span><span class="keyword3"><span class="command"><span>show</span></span></span><span> </span><span class="var"><span class="quoted"><span class="var"><span>?case</span></span></span></span><span>
    </span><span class="keyword1"><span class="command"><span>proof</span></span></span><span class="main"><span>(</span></span><span class="operator"><span>cases</span></span><span class="main"><span>)</span></span><span>
      </span><span class="keyword3"><span class="command"><span>case</span></span></span><span> </span><span class="entity_def" id="offset_12126..12127">3</span><span>
      </span><span class="keyword3"><span class="command"><span>obtain</span></span></span><span> </span><span class="skolem"><span class="skolem"><span>i</span></span></span><span> </span><span class="keyword2"><span class="keyword"><span>where</span></span></span><span> </span><span class="entity_def" id="offset_12147..12153">bounds</span><span class="main"><span>:</span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span>fib</span><span> </span><span class="skolem"><span>i</span></span><span> </span><span class="main"><span>≤</span></span><span> </span><span class="skolem"><span>n</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span>fib</span><span class="main"><span>(</span></span><span>Suc</span><span> </span><span class="skolem"><span>i</span></span><span class="main"><span>)</span></span><span> </span><span class="main"><span>&gt;</span></span><span> </span><span class="skolem"><span>n</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="numeral"><span>2</span></span><span> </span><span class="main"><span>≤</span></span><span> </span><span class="skolem"><span>i</span></span><span>"</span></span></span><span> 
        </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>betw_fibs</span><span> </span><span>nat_ge_2_fib_idx_bound</span><span> </span><span>3</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>blast</span></span><span>
      </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="entity_def" id="offset_12258..12269">last_idx_eq</span><span class="main"><span>:</span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>c'</span></span><span> </span><span class="skolem"><span>k'</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="skolem"><span>i</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>c</span></span><span> </span><span class="skolem"><span>k</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="skolem"><span>i</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>c'</span></span><span> </span><span class="skolem"><span>k'</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="free"><span>c</span></span><span> </span><span class="skolem"><span>k</span></span><span>"</span></span></span><span>
        </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>last_fib_sum_index_constraint</span><span class="main"><span>[</span></span><span class="operator"><span>OF</span></span><span> </span><span>3</span><span class="main"><span>]</span></span><span> </span><span>IH</span><span class="main"><span>(</span></span><span>6-8</span><span class="main"><span>)</span></span><span> </span><span>IH</span><span class="main"><span>(</span></span><span>3-5</span><span class="main"><span>)</span></span><span> </span><span>bounds</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>blast</span></span><span class="main"><span class="keyword3"><span>+</span></span></span><span>
      </span><span class="keyword1"><span class="command"><span>then</span></span></span><span> </span><span class="keyword3"><span class="command"><span>show</span></span></span><span> </span><span class="var"><span class="quoted"><span class="var"><span>?thesis</span></span></span></span><span>
      </span><span class="keyword1"><span class="command"><span>proof</span></span></span><span class="main"><span>(</span></span><span class="operator"><span>cases</span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span>is_fib</span><span> </span><span class="skolem"><span>n</span></span><span>"</span></span></span><span class="main"><span>)</span></span><span>
        </span><span class="keyword3"><span class="command"><span>case</span></span></span><span> </span><span>True</span><span>
        </span><span class="keyword1"><span class="command"><span>hence</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span>fib</span><span> </span><span class="skolem"><span>i</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="skolem"><span>n</span></span><span>"</span></span></span><span> 
          </span><span class="keyword1"><span class="command"><span>unfolding</span></span></span><span> </span><span>is_fib_def</span><span> </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>bounds</span><span> </span><span>IH</span><span class="main"><span>(</span></span><span>2-8</span><span class="main"><span>)</span></span><span> </span><span>fib_mono</span><span> </span><span>leD</span><span> </span><span>nle_le</span><span> </span><span>not_less_eq_eq</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>metis</span></span><span>
        </span><span class="keyword1"><span class="command"><span>hence</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="skolem"><span>k</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="main"><span>0</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>c</span></span><span> </span><span class="main"><span>0</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="skolem"><span>i</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="skolem"><span>k'</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="main"><span>0</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>c'</span></span><span> </span><span class="main"><span>0</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="skolem"><span>i</span></span><span>"</span></span></span><span>
          </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>fib_unique_fib_sum</span><span> </span><span>3</span><span> </span><span>IH</span><span class="main"><span>(</span></span><span>3-8</span><span class="main"><span>)</span></span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>metis</span></span><span class="main"><span class="keyword3"><span>+</span></span></span><span>
          </span><span class="keyword1"><span class="command"><span>then</span></span></span><span> </span><span class="keyword3"><span class="command"><span>show</span></span></span><span> </span><span class="var"><span class="quoted"><span class="var"><span>?thesis</span></span></span></span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>simp</span></span><span>
      </span><span class="keyword1"><span class="command"><span>next</span></span></span><span>
        </span><span class="keyword3"><span class="command"><span>case</span></span></span><span> </span><span class="entity_def" id="offset_12730..12735">False</span><span>
        </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="skolem"><span>k</span></span><span> </span><span class="main"><span>&gt;</span></span><span> </span><span class="main"><span>0</span></span><span>"</span></span></span><span> 
          </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>IH</span><span class="main"><span>(</span></span><span>3</span><span class="main"><span>)</span></span><span> </span><span>False</span><span> </span><span class="keyword1"><span class="command"><span>unfolding</span></span></span><span> </span><span>is_fib_def</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>fastforce</span></span><span>
        </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="skolem"><span>k'</span></span><span> </span><span class="main"><span>&gt;</span></span><span> </span><span class="main"><span>0</span></span><span>"</span></span></span><span>
          </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>IH</span><span class="main"><span>(</span></span><span>6</span><span class="main"><span>)</span></span><span> </span><span>False</span><span>  </span><span class="keyword1"><span class="command"><span>unfolding</span></span></span><span> </span><span>is_fib_def</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>fastforce</span></span><span>
        </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="main"><span>0</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span class="skolem"><span>n</span></span><span> </span><span class="main"><span>-</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>c</span></span><span> </span><span class="skolem"><span>k</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span> </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>False</span><span> </span><span>bounds</span><span> </span><span>last_idx_eq</span><span class="main"><span>(</span></span><span>2</span><span class="main"><span>)</span></span><span> </span><span class="keyword1"><span class="command"><span>unfolding</span></span></span><span> </span><span>is_fib_def</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>fastforce</span></span><span>
        </span><span class="keyword1"><span class="command"><span>moreover</span></span></span><span> </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="skolem"><span>n</span></span><span> </span><span class="main"><span>-</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>c</span></span><span> </span><span class="skolem"><span>k</span></span><span class="main"><span>)</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span class="skolem"><span>n</span></span><span>"</span></span></span><span> 
          </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>bounds</span><span> </span><span>last_idx_eq</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="main"><span>(</span></span><span class="operator"><span>simp</span></span><span> </span><span class="quasi_keyword"><span>add</span></span><span class="main"><span class="main"><span>:</span></span></span><span> </span><span>dual_order.strict_trans1</span><span> </span><span>fib_neq_0_nat</span><span class="main"><span>)</span></span><span>
        </span><span class="keyword1"><span class="command"><span>moreover</span></span></span><span> </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="skolem"><span>n</span></span><span> </span><span class="main"><span>-</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>c</span></span><span> </span><span class="skolem"><span>k</span></span><span class="main"><span>)</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="main"><span>(</span></span><span class="main"><span>∑</span></span><span class="bound"><span>i</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="skolem"><span>k</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span class="main"><span>.</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>c</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>)</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span> 
          </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>sum.atLeast0_atMost_Suc</span><span class="main"><span>[</span></span><span class="operator"><span>of</span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="main"><span>λ</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>.</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>c</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="skolem"><span>k</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span>"</span></span></span><span class="main"><span>]</span></span><span> </span><span>Suc_diff_1</span><span> </span><span class="quoted"><span class="quoted"><span>‹</span><span class="skolem"><span>k</span></span><span> </span><span class="main"><span>&gt;</span></span><span> </span><span class="main"><span>0</span></span><span>›</span></span></span><span> </span><span>IH</span><span class="main"><span>(</span></span><span>3</span><span class="main"><span>)</span></span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>simp</span></span><span>
        </span><span class="keyword1"><span class="command"><span>moreover</span></span></span><span> </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="skolem"><span>n</span></span><span> </span><span class="main"><span>-</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>c'</span></span><span> </span><span class="skolem"><span>k'</span></span><span> </span><span class="main"><span>)</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="main"><span>(</span></span><span class="main"><span>∑</span></span><span class="bound"><span>i</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="skolem"><span>k'</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span class="main"><span>.</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>c'</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>)</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span> 
          </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>sum.atLeast0_atMost_Suc</span><span class="main"><span>[</span></span><span class="operator"><span>of</span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="main"><span>λ</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>.</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>c'</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="skolem"><span>k'</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span>"</span></span></span><span class="main"><span>]</span></span><span> </span><span>Suc_diff_1</span><span> </span><span class="quoted"><span class="quoted"><span>‹</span><span class="skolem"><span>k'</span></span><span> </span><span class="main"><span>&gt;</span></span><span> </span><span class="main"><span>0</span></span><span>›</span></span></span><span> </span><span>IH</span><span class="main"><span>(</span></span><span>6</span><span class="main"><span>)</span></span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>simp</span></span><span>
        </span><span class="keyword1"><span class="command"><span>moreover</span></span></span><span> </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span>inc_seq_on</span><span> </span><span class="free"><span>c</span></span><span> </span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="skolem"><span>k</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span> </span><span class="main"><span>-</span></span><span> </span><span class="main"><span>1</span></span><span class="main"><span>{'}'}</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="main"><span>∀</span></span><span class="bound"><span>i</span></span><span class="main"><span>∈</span></span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="skolem"><span>k</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span class="main"><span>{'}'}</span></span><span class="main"><span>.</span></span><span> </span><span class="numeral"><span>2</span></span><span> </span><span class="main"><span>≤</span></span><span> </span><span class="free"><span>c</span></span><span> </span><span class="bound"><span>i</span></span><span>"</span></span></span><span>
          </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>IH</span><span class="main"><span>(</span></span><span>4</span><span class="main"><span>,</span></span><span>5</span><span class="main"><span>)</span></span><span> </span><span class="keyword1"><span class="command"><span>unfolding</span></span></span><span> </span><span>inc_seq_on_def</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>auto</span></span><span>
        </span><span class="keyword1"><span class="command"><span>moreover</span></span></span><span> </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span>inc_seq_on</span><span> </span><span class="free"><span>c'</span></span><span> </span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="skolem"><span>k'</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span> </span><span class="main"><span>-</span></span><span> </span><span class="main"><span>1</span></span><span class="main"><span>{'}'}</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="main"><span>∀</span></span><span class="bound"><span>i</span></span><span class="main"><span>∈</span></span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="skolem"><span>k'</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span class="main"><span>{'}'}</span></span><span class="main"><span>.</span></span><span> </span><span class="numeral"><span>2</span></span><span> </span><span class="main"><span>≤</span></span><span> </span><span class="free"><span>c'</span></span><span> </span><span class="bound"><span>i</span></span><span>"</span></span></span><span>
          </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>IH</span><span class="main"><span>(</span></span><span>7</span><span class="main"><span>,</span></span><span>8</span><span class="main"><span>)</span></span><span> </span><span class="keyword1"><span class="command"><span>unfolding</span></span></span><span> </span><span>inc_seq_on_def</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>auto</span></span><span>
        </span><span class="keyword1"><span class="command"><span>ultimately</span></span></span><span> </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="skolem"><span>k</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="skolem"><span>k'</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span> </span><span class="main"><span>∧</span></span><span> </span><span class="main"><span>(</span></span><span class="main"><span>∀</span></span><span class="bound"><span>i</span></span><span class="main"><span>∈</span></span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="skolem"><span>k</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span class="main"><span>{'}'}</span></span><span class="main"><span>.</span></span><span> </span><span class="free"><span>c</span></span><span> </span><span class="bound"><span>i</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="free"><span>c'</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span>
          </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>IH</span><span class="main"><span>(</span></span><span>1</span><span class="main"><span>)</span></span><span> </span><span class="keyword1"><span class="command"><span>unfolding</span></span></span><span> </span><span>last_idx_eq</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>blast</span></span><span> 
        </span><span class="keyword1"><span class="command"><span>then</span></span></span><span> </span><span class="keyword3"><span class="command"><span>show</span></span></span><span> </span><span class="var"><span class="quoted"><span class="var"><span>?thesis</span></span></span></span><span>
          </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>IH</span><span class="main"><span>(</span></span><span>1</span><span class="main"><span>)</span></span><span> </span><span>last_idx_eq</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="main"><span>(</span></span><span class="operator"><span>metis</span></span><span> </span><span>One_nat_def</span><span> </span><span>Suc_pred</span><span> </span><span class="quoted"><span class="quoted"><span>‹</span><span class="main"><span>0</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span class="skolem"><span>k'</span></span><span>›</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>‹</span><span class="main"><span>0</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span class="skolem"><span>k</span></span><span>›</span></span></span><span> </span><span>atLeastAtMost_iff</span><span> </span><span>le_Suc_eq</span><span class="main"><span>)</span></span><span>
      </span><span class="keyword1"><span class="command"><span>qed</span></span></span><span>
    </span><span class="keyword1"><span class="command"><span>qed</span></span></span><span class="main"><span>(</span></span><span class="operator"><span>insert</span></span><span> </span><span>IH</span><span> </span><span>one_unique_fib_sum</span><span class="main"><span class="keyword3"><span>,</span></span></span><span> </span><span class="operator"><span>auto</span></span><span class="main"><span>)</span></span><span>
  </span><span class="keyword1"><span class="command"><span>qed</span></span></span>
</pre>
<p>
  My approach to the formalization of the uniqueness proof was to assume that two Zeckendorf representations of <Katex>N</Katex> exist and show that the two mappings <Katex>c</Katex> and <Katex>c'</Katex> are identical.
  As in the previous proof, I use induction over <Katex>N</Katex> with Isabelle's <code>nat_less_induct</code> induction rule. Additionally, I introduce <Katex>k</Katex> and <Katex>k'</Katex> as arbitrary variables. The <code>arbitrary</code> keyword in the induction rule ensures that <Katex>k</Katex> and <Katex>k'</Katex> remain universally quantified throughout the proof. This is necessary to show <Katex>k = k'</Katex>. Next, I construct a case distinction on <Katex>N</Katex>, where the cases for <Katex>N=0</Katex> and <Katex>N=1</Katex> can be solved automatically by Isabelle. In the third case, I further distinguish whether <Katex>N</Katex> is a Fibonacci number. If <Katex>N</Katex> is a Fibonacci number, we can use the fact that Fibonacci numbers trivially have a unique representation. If <Katex>N</Katex> is not a Fibonacci number, we can use the induction hypothesis and derive a Zeckendorf representation for <Katex>N - F_i</Katex>.
  
  From the induction hypothesis, we can also conclude that <Katex>k - 1 = k' - 1</Katex> and <Katex>c_i = c_i'</Katex> for all <Katex>0 \le i \le k-1</Katex>. Remember, our goal is to prove <Katex>k = k'</Katex> and <Katex>c_i = c_i'</Katex> for all <Katex>0 \le i \le k</Katex>. Since <Katex>k = k'</Katex> trivially follows from <Katex>k - 1 = k' - 1</Katex>, the main goal is to show <Katex>c_k = c_{"{k'}"}</Katex>. Isabelle can prove this by using the following equation.
</p>
<Katex displayMode>
  N - F_{"{c_k}"} = \sum_{"{j=0}"}^k F_{"{c_j}"}  = \sum_{"{j=0}"}^{"{k'}"} F_{"{c'_j}"} = N - F_{"{c_k'}"}
</Katex>
<p>
  This concludes the formalization of the Zeckendorf theorem proof. I am sure that this is not the most elegant solution. A week after finishing this formalization, I had the idea to use lists of indices in the summation. I believe this would simplify Isabelle's reasoning because I could remove some auxiliary lemmas and the domain from the <code>inc_seq_on</code> property. If I have time in the future, I may redo the formalization in a cleaner version.
</p>
<!---
<pre class="source">
  <span class="keyword1"><span class="command"><span class="entity_def" id="offset_6962..6967">lemma</span></span></span><span> </span><span class="entity_def" id="Zeckendorf.last_fib_sum_index_constraint|fact"><span class="entity_def" id="Zeckendorf.last_fib_sum_index_constraint|thm"><span>last_fib_sum_index_constraint</span></span></span><span class="main"><span>:</span></span><span>
    </span><span class="keyword2"><span class="keyword"><span>assumes</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>n</span></span><span> </span><span class="main"><span>≥</span></span><span> </span><span class="numeral"><span>2</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>n</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="main"><span>(</span></span><span class="main"><span>∑</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>=</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="free"><span>k</span></span><span class="main"><span>.</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>c</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>)</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span>inc_seq_on</span><span> </span><span class="free"><span>c</span></span><span> </span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="free"><span>k</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span class="main"><span>{'}'}</span></span><span>"</span></span></span><span> 
    </span><span class="keyword2"><span class="keyword"><span>assumes</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="main"><span>∀</span></span><span class="bound"><span>i</span></span><span class="main"><span>∈</span></span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="free"><span>k</span></span><span class="main"><span>{'}'}</span></span><span class="main"><span>.</span></span><span> </span><span class="free"><span>c</span></span><span> </span><span class="bound"><span>i</span></span><span> </span><span class="main"><span>≥</span></span><span> </span><span class="numeral"><span>2</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span>fib</span><span> </span><span class="free"><span>i</span></span><span> </span><span class="main"><span>≤</span></span><span> </span><span class="free"><span>n</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span>fib</span><span class="main"><span>(</span></span><span>Suc</span><span> </span><span class="free"><span>i</span></span><span class="main"><span>)</span></span><span> </span><span class="main"><span>&gt;</span></span><span> </span><span class="free"><span>n</span></span><span>"</span></span></span><span>
    </span><span class="keyword2"><span class="keyword"><span>shows</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>c</span></span><span> </span><span class="free"><span>k</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="free"><span>i</span></span><span>"</span></span></span><span>
  </span><span class="keyword1"><span class="command"><span>proof</span></span></span><span> </span><span class="operator"><span>-</span></span><span>
    </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="numeral"><span>2</span></span><span> </span><span class="main"><span>≤</span></span><span> </span><span class="free"><span>i</span></span><span>"</span></span></span><span> </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>assms</span><span class="main"><span>(</span></span><span>1</span><span class="main"><span>,</span></span><span>5</span><span class="main"><span>,</span></span><span>6</span><span class="main"><span>)</span></span><span> </span><span>nat_ge_2_fib_idx_bound</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>simp</span></span><span> 
    </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>c</span></span><span> </span><span class="free"><span>k</span></span><span> </span><span class="main"><span>&gt;</span></span><span> </span><span class="free"><span>i</span></span><span> </span><span class="main"><span>⟶</span></span><span> </span><span>False</span><span>"</span></span></span><span>
      </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>smaller_index_implies_fib_le</span><span> </span><span>assms</span><span> 
      </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="main"><span>(</span></span><span class="operator"><span>metis</span></span><span> </span><span>bot_nat_0.extremum</span><span> </span><span>leD</span><span> </span><span>sum.last_plus</span><span> </span><span>trans_le_add1</span><span class="main"><span>)</span></span><span>
    </span><span class="keyword1"><span class="command"><span>moreover</span></span></span><span> </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>c</span></span><span> </span><span class="free"><span>k</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span class="free"><span>i</span></span><span> </span><span class="main"><span>⟶</span></span><span> </span><span>False</span><span>"</span></span></span><span>
    </span><span class="keyword1"><span class="command"><span>proof</span></span></span><span> 
      </span><span class="keyword3"><span class="command"><span>assume</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>c</span></span><span> </span><span class="free"><span>k</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span class="free"><span>i</span></span><span>"</span></span></span><span>
      </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="entity_def" id="offset_7432..7435">seq</span><span class="main"><span>:</span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span>inc_seq_on</span><span> </span><span class="free"><span>c</span></span><span> </span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="free"><span>k</span></span><span> </span><span class="main"><span>-</span></span><span> </span><span class="main"><span>1</span></span><span> </span><span class="main"><span>-</span></span><span> </span><span class="main"><span>1</span></span><span class="main"><span>{'}'}</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="main"><span>∀</span></span><span class="bound"><span>i</span></span><span class="main"><span>∈</span></span><span class="main"><span>{'{'}</span></span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="free"><span>k</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span class="main"><span>{'}'}</span></span><span class="main"><span>.</span></span><span> </span><span class="numeral"><span>2</span></span><span> </span><span class="main"><span>≤</span></span><span> </span><span class="free"><span>c</span></span><span> </span><span class="bound"><span>i</span></span><span>"</span></span></span><span>
        </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>assms</span><span> </span><span class="keyword1"><span class="command"><span>unfolding</span></span></span><span> </span><span>inc_seq_on_def</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>simp</span></span><span class="main"><span class="keyword3"><span>+</span></span></span><span>
      </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>k</span></span><span> </span><span class="main"><span>&gt;</span></span><span> </span><span class="main"><span>0</span></span><span>"</span></span></span><span>
        </span><span class="keyword1"><span class="command"><span>by</span></span></span><span class="main"><span>(</span></span><span class="operator"><span>rule</span></span><span> </span><span>ccontr</span><span class="main"><span class="keyword3"><span>,</span></span></span><span> </span><span class="operator"><span>insert</span></span><span> </span><span class="quoted"><span class="quoted"><span>‹</span><span class="free"><span>c</span></span><span> </span><span class="free"><span>k</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span class="free"><span>i</span></span><span>›</span></span></span><span> </span><span>assms</span><span> </span><span>fib_index_strict_mono</span><span> </span><span>leD</span><span class="main"><span class="keyword3"><span>,</span></span></span><span> </span><span class="operator"><span>auto</span></span><span class="main"><span>)</span></span><span>
      </span><span class="keyword1"><span class="command"><span>hence</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>c</span></span><span> </span><span class="main"><span>(</span></span><span class="free"><span>k</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span class="main"><span>)</span></span><span> </span><span class="main"><span>+</span></span><span> </span><span class="main"><span>1</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span class="free"><span>c</span></span><span> </span><span class="free"><span>k</span></span><span>"</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>c</span></span><span> </span><span class="main"><span>(</span></span><span class="free"><span>k</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span class="main"><span>)</span></span><span> </span><span class="main"><span>+</span></span><span> </span><span class="numeral"><span>3</span></span><span> </span><span class="main"><span>≤</span></span><span> </span><span class="free"><span>i</span></span><span>"</span></span></span><span>
        </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>‹</span><span class="free"><span>c</span></span><span> </span><span class="free"><span>k</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span class="free"><span>i</span></span><span>›</span></span></span><span> </span><span>assms</span><span> </span><span class="keyword1"><span class="command"><span>unfolding</span></span></span><span> </span><span>inc_seq_on_def</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>force</span></span><span class="main"><span class="keyword3"><span>+</span></span></span><span>
      </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="main"><span>(</span></span><span class="main"><span>∑</span></span><span class="bound"><span>i</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="free"><span>k</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span class="main"><span>.</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>c</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>)</span></span><span class="main"><span>)</span></span><span> </span><span class="main"><span>+</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>c</span></span><span> </span><span class="free"><span>k</span></span><span class="main"><span>)</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="main"><span>(</span></span><span class="main"><span>∑</span></span><span class="bound"><span>i</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="free"><span>k</span></span><span class="main"><span>.</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>c</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>)</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span>
        </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>sum.atLeast0_atMost_Suc</span><span> </span><span>Suc_pred'</span><span class="main"><span>[</span></span><span class="operator"><span>OF</span></span><span> </span><span class="quoted"><span class="quoted"><span>‹</span><span class="free"><span>k</span></span><span> </span><span class="main"><span>&gt;</span></span><span> </span><span class="main"><span>0</span></span><span>›</span></span></span><span class="main"><span>]</span></span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>metis</span></span><span>
      </span><span class="keyword1"><span class="command"><span>moreover</span></span></span><span> </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span>fib</span><span> </span><span class="main"><span>(</span></span><span>Suc</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>c</span></span><span> </span><span class="main"><span>(</span></span><span class="free"><span>k</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span class="main"><span>)</span></span><span class="main"><span>)</span></span><span class="main"><span>)</span></span><span> </span><span class="main"><span>≤</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>i</span></span><span class="main"><span>-</span></span><span class="numeral"><span>2</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span>
        </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>‹</span><span class="free"><span>c</span></span><span> </span><span class="free"><span>k</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span class="free"><span>i</span></span><span>›</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>‹</span><span class="free"><span>c</span></span><span> </span><span class="main"><span>(</span></span><span class="free"><span>k</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span class="main"><span>)</span></span><span> </span><span class="main"><span>+</span></span><span> </span><span class="main"><span>1</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span class="free"><span>c</span></span><span> </span><span class="free"><span>k</span></span><span>›</span></span></span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="main"><span>(</span></span><span class="operator"><span>simp</span></span><span> </span><span class="quasi_keyword"><span>add</span></span><span class="main"><span class="main"><span>:</span></span></span><span> </span><span>fib_mono</span><span class="main"><span>)</span></span><span>
      </span><span class="keyword1"><span class="command"><span>moreover</span></span></span><span> </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>c</span></span><span> </span><span class="free"><span>k</span></span><span class="main"><span>)</span></span><span> </span><span class="main"><span>≤</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>i</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span>
        </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>‹</span><span class="free"><span>c</span></span><span> </span><span class="free"><span>k</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span class="free"><span>i</span></span><span>›</span></span></span><span> </span><span>fib_mono</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>fastforce</span></span><span>
      </span><span class="keyword1"><span class="command"><span>ultimately</span></span></span><span> </span><span class="keyword1"><span class="command"><span>have</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="main"><span>(</span></span><span class="main"><span>∑</span></span><span class="bound"><span>i</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="free"><span>k</span></span><span class="main"><span>.</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>c</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>)</span></span><span class="main"><span>)</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>i</span></span><span class="main"><span>-</span></span><span class="main"><span>1</span></span><span class="main"><span>)</span></span><span> </span><span class="main"><span>+</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>i</span></span><span class="main"><span>-</span></span><span class="numeral"><span>2</span></span><span class="main"><span>)</span></span><span>"</span></span></span><span>
        </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>assms</span><span> </span><span class="quoted"><span class="quoted"><span>‹</span><span class="free"><span>c</span></span><span> </span><span class="free"><span>k</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span class="free"><span>i</span></span><span>›</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>‹</span><span class="free"><span>k</span></span><span> </span><span class="main"><span>&gt;</span></span><span> </span><span class="main"><span>0</span></span><span>›</span></span></span><span> </span><span>fib_sum_upper_bound</span><span class="main"><span>[</span></span><span class="operator"><span>OF</span></span><span> </span><span>seq</span><span class="main"><span class="main"><span>(</span></span></span><span>1</span><span class="main"><span class="main"><span>)</span></span></span><span> </span><span>seq</span><span class="main"><span class="main"><span>(</span></span></span><span>2</span><span class="main"><span class="main"><span>)</span></span></span><span class="main"><span>]</span></span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>simp</span></span><span>
      </span><span class="keyword1"><span class="command"><span>hence</span></span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="main"><span>(</span></span><span class="main"><span>∑</span></span><span class="bound"><span>i</span></span><span> </span><span class="main"><span>=</span></span><span> </span><span class="main"><span>0</span></span><span class="main"><span>..</span></span><span class="free"><span>k</span></span><span class="main"><span>.</span></span><span> </span><span>fib</span><span> </span><span class="main"><span>(</span></span><span class="free"><span>c</span></span><span> </span><span class="bound"><span>i</span></span><span class="main"><span>)</span></span><span class="main"><span>)</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span>fib</span><span> </span><span class="free"><span>i</span></span><span>"</span></span></span><span>
        </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>fib.simps</span><span class="main"><span>(</span></span><span>3</span><span class="main"><span>)</span></span><span class="main"><span>[</span></span><span class="operator"><span>of</span></span><span> </span><span class="quoted"><span class="quoted"><span>"</span><span class="free"><span>i</span></span><span class="main"><span>-</span></span><span class="numeral"><span>2</span></span><span>"</span></span></span><span class="main"><span>]</span></span><span> </span><span>assms</span><span class="main"><span>(</span></span><span>4</span><span class="main"><span>)</span></span><span> </span><span class="quoted"><span class="quoted"><span>‹</span><span class="free"><span>c</span></span><span> </span><span class="free"><span>k</span></span><span> </span><span class="main"><span>&lt;</span></span><span> </span><span class="free"><span>i</span></span><span>›</span></span></span><span> 
        </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="main"><span>(</span></span><span class="operator"><span>metis</span></span><span> </span><span>add_2_eq_Suc</span><span> </span><span>diff_Suc_1</span><span> </span><span class="quoted"><span class="quoted"><span>‹</span><span class="numeral"><span>2</span></span><span> </span><span class="main"><span>≤</span></span><span> </span><span class="free"><span>i</span></span><span>›</span></span></span><span> </span><span>le_add_diff_inverse</span><span class="main"><span>)</span></span><span>
      </span><span class="keyword1"><span class="command"><span>then</span></span></span><span> </span><span class="keyword3"><span class="command"><span>show</span></span></span><span> </span><span class="quoted"><span>False</span></span><span>
        </span><span class="keyword1"><span class="command"><span>using</span></span></span><span> </span><span>assms</span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>simp</span></span><span>
      </span><span class="keyword1"><span class="command"><span>qed</span></span></span><span>
      </span><span class="keyword1"><span class="command"><span>ultimately</span></span></span><span> </span><span class="keyword3"><span class="command"><span>show</span></span></span><span> </span><span class="var"><span class="quoted"><span class="var"><span>?thesis</span></span></span></span><span> </span><span class="keyword1"><span class="command"><span>by</span></span></span><span> </span><span class="operator"><span>simp</span></span><span>
    </span><span class="keyword1"><span class="command"><span>qed</span></span></span>
</pre>
--->
    </ArticleSection>
    <References citations={citations}/>
</ArticleTemplate>